debug: false
management.endpoints.web.exposure.include: "*"

logging:
  level:
    com.example.springbootplayground: debug
    org.springframework.web.servlet: debug
    org.hibernate.type.descriptor.sql.BasicBinder: trace

spring:
  datasource:
    url: jdbc:h2:mem:testdb
    username: sa
  jpa:
    open-in-view: false
    defer-datasource-initialization: true
    hibernate.ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate.format_sql: true
  sql.init.mode: always
